name: counter_bloc_pattern_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  weather_repository:
    path: packages/weather_repository

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  test: ^1.0.0
  very_good_analysis: ^3.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/
